# Create Array

In [35]:
import numpy as np

# array 1 chieu
students = np.array(["An", "Binh", "Nhi", "Tuan", "Khoa", "Bao"])
subjects = np.array(["Python", "Math", "Machine Learning", "AI"])

# array 2 chieu
scores = np.array([
    [8,9,5,7],
    [6,5,7,5],
    [8,9,5,9],
    [10,7,5,8],
    [7,8,6,9],
    [5,9,7,6]
])

print(students)
print(subjects)
print(scores)

['An' 'Binh' 'Nhi' 'Tuan' 'Khoa' 'Bao']
['Python' 'Math' 'Machine Learning' 'AI']
[[ 8  9  5  7]
 [ 6  5  7  5]
 [ 8  9  5  9]
 [10  7  5  8]
 [ 7  8  6  9]
 [ 5  9  7  6]]


In [ ]:
# Attribute: shape, dtype, size, ndim
# hiển thị số dòng và số cột của scores
# số chiều của mảng
# tổng số phần tử
# kiểu dữ liệu của các phần tử
print("Row and Column: ", scores.shape)
print("Number of dimensions: ", scores.ndim)
print("Number of elements: ", scores.size)
print("Data Type: ", scores.dtype)

In [ ]:
# index
# lay diem Python của anh An
# lay toan bo diem cua anh Tuan
# lay diem AI cua Nhi
# lay toan bo diem cua sinh vien cuoi cung
print("Python cua An: ", scores[0,0])
print("Toan bo diem cua Tuan: ", scores[3])
print("Diem AI cua Nhi: ", scores[2,3])
print("Toan bo diem cua sv cuoi cung: ", scores[-1])

In [ ]:
# slicing
# hien thi diem cua 3 sv dau tien
# hien thi diem cua 2 mon dau tien cua tat ca sv
# hien thi diem ML va AI cua tat ca sv
print("Diem cua 3 sv dau tien: \n", scores[0:3, :])
print("Diem cua 3 sv dau tien: \n", scores[0:3])
print("Diem cua 3 sv dau tien: \n", scores[:3])

print("Diem cua 2 mon dau tien: \n", scores[:, 0:2])

print("Diem cua ML va AI: \n", scores[:, 2:4])
print("Diem cua ML va AI: \n", scores[:, 2:])
print("Diem cua ML va AI: \n", scores[:, -2:])


In [36]:
# Boolean Indexing
# hien thi sv co diem Python nho hon 8
python_scores = scores[:,0]
print("Diem Python: \n", python_scores)
print("Diem Python < 8: ", python_scores[python_scores < 8])
print("Sv co diem python < 8: ", students[python_scores < 8])

Diem Python: 
 [ 8  6  8 10  7  5]
Diem Python < 8:  [6 7 5]
Sv co diem python < 8:  ['Binh' 'Khoa' 'Bao']


In [38]:
# reshape(): chuyen mang 1 chieu thanh 2 chieu
python_reshape = python_scores.reshape(2,3)
print("python_reshape: \n", python_reshape)
# flatten(): chuyen tra nguoc lai 2 chieu thanh 1 chieu
python_flatten = python_reshape.flatten()
print("python_flatten: \n", python_flatten)

python_reshape: 
 [[ 8  6  8]
 [10  7  5]]
python_flatten: 
 [ 8  6  8 10  7  5]


In [39]:
# Tranposing: chuyen vi, chuyen dong thanh cot va cot thanh dong
matrix = np.array([[1,2,3], [4,5,6]])
print("matrix: \n", matrix)
print("matrixT: \n", matrix.T)

matrix: 
 [[1 2 3]
 [4 5 6]]
matrixT: 
 [[1 4]
 [2 5]
 [3 6]]


In [41]:
# Aggregate Function: sum, min, max, mean, axis
# Tinh diem trung binh cua tung sinh vien
student_avg = np.mean(scores, axis = 1)
print("student_avg", student_avg)

for i in range(len(students)):
    print(students[i], ":" , student_avg[i])

student_avg [7.25 5.75 7.75 7.5  7.5  6.75]
An : 7.25
Binh : 5.75
Nhi : 7.75
Tuan : 7.5
Khoa : 7.5
Bao : 6.75


In [43]:
# diem cao nhat cua toan bo
print("Diem cao nhat: ", np.max(scores))
# diem thap nhat cua toan bo
print("Diem thap nhat: ", np.min(scores))
# diem cao nhat cua tung mon hoc
print("Diem cao nhat tung mon hoc: ", np.max(scores, axis =0))

Diem cao nhat:  10
Diem thap nhat:  5
Diem cao nhat tung mon hoc:  [10  9  7  9]


In [44]:
# broadcasting: mo rong mang
# do di hoc day du, cong them moi mon cho moi ban 1 diem
bonus = 1
new_scores = scores + bonus
print("Diem sau khi cong: \n ", new_scores)

Diem sau khi cong: 
  [[ 9 10  6  8]
 [ 7  6  8  6]
 [ 9 10  6 10]
 [11  8  6  9]
 [ 8  9  7 10]
 [ 6 10  8  7]]


In [ ]:
# np.dot() hoac @: nhan ma tran
# tinh diem tong ket co trong so 
'''
Python = 20%
Math = 20%
ML = 35%
AI = 25%
'''
'''
scores = (6x4)
w = (4x1)
-> final_scores = (6x1)
'''
w = np.array([0.2, 0.2, 0.35, 0.25])
final_scores = scores @ w
print("final_scores:", final_scores)


final_scores: [6.9  5.9  7.4  7.15 7.35 6.75]


In [ ]:
# random(): mo phong du lieu
# np.random.seed(10)
print("Random [0-1): ", np.random.rand())
print("Random (2x2): \n", np.random.rand(2,2))
print("Random [10-99] lay 6 so: \n ", np.random.randint(10,100,6))

Random [0-1):  0.3466906590240366
Random (2x2): 
 [[0.57766425 0.16835294]
 [0.0379717  0.8171767 ]]
Random [0-9] lay 6 so: 
  [93 47 81 98 25 65]


In [ ]:
# Fancy Indexing
# hien thi diem cua 2 mon Math va AI
# lay het tat ca cac dong :
# lay cot index 1 va index 3: [1,3]
print("Diem cua Math va AI: \n", scores[:,[1,3]])

Diem cua Math va AI: 
 [[9 7]
 [5 5]
 [9 9]
 [7 8]
 [8 9]
 [9 6]]


In [90]:
# luu va doc file array
np.save("students.npy", students)
# doc du lieu tu file binary
students_load = np.load("students.npy")
print("students_load: ", students_load)
# luu du lieu file txt
np.savetxt("scores.txt", scores, delimiter=",")
# doc du lieu
scores_load = np.loadtxt("scores.txt", delimiter=",")
print("scores_load: \n", scores_load)

students_load:  ['An' 'Binh' 'Nhi' 'Tuan' 'Khoa' 'Bao']
scores_load: 
 [[ 8.  9.  5.  7.]
 [ 6.  5.  7.  5.]
 [ 8.  9.  5.  9.]
 [10.  7.  5.  8.]
 [ 7.  8.  6.  9.]
 [ 5.  9.  7.  6.]]
